### ISSUE TITLE
Mkdir command not working

### ISSUE THREAD

**Issue by Alestrio** [Alestrio/ProBotE#5]
On server

**Comment by Alestrio** [comment]
Seems related to parseFoderArgument method (surely due to today's merge)

**Comment by Alestrio** [comment]
![Capture d’écran du 2020-05-19 14-01-11](https://user-images.githubusercontent.com/15311023/82324053-469f0100-99d9-11ea-848a-bdd1e72529b3.png)
Don't know about the logs, gonna paste it in next comment

**Comment by Alestrio** [comment]
```
TypeError: 'int' object is not iterable
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/eribel/.local/lib/python3.6/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/eribel/ProBotE/discordactions.py", line 59, in on_message
    folderId = self.drive.parseFolderArgument(int(splittedMsg[2]), int(splittedMsg[3]))
  File "/home/eribel/ProBotE/gdrive.py", line 50, in parseFolderArgument
    primaryFolderId, secondaryFolderId, folderId = -1
TypeError: 'int' object is not iterable
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/eribel/.local/lib/python3.6/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/eribel/ProBotE/discordactions.py", line 59, in on_message
    folderId = self.drive.parseFolderArgument(int(splittedMsg[2]), int(splittedMsg[3]))
  File "/home/eribel/ProBotE/gdrive.py", line 50, in parseFolderArgument
    primaryFolderId, secondaryFolderId, folderId = -1
TypeError: 'int' object is not iterable
```

Not gonna fix it now, will wait a bit, but I know what this is, to be continued
-> Due to last PRs when I was working on parse method, shouldn't have been merged
